::TLW.ItemPath <-  //same as defs, but im lazy
{
	Path = {
		Alp = "scripts/items/misc/corpse_alp_item"
		LegendDemonAlp = "scripts/items/misc/corpse_alp2_item"
        LegendDemonHound = "scripts/items/misc/corpse_demonhound_item"
		Direwolf = "scripts/items/misc/corpse_direwolf_item"
        LegendWhiteDirewolf = "scripts/items/misc/corpse_direwolf2_item"
        Ghost = "scripts/items/misc/corpse_ghost_item"
        LegendBanshee = "scripts/items/misc/corpse_ghost2_item"
        Ghoul = "scripts/items/misc/corpse_ghoul_item"
        LegendSkinGhoul = "scripts/items/misc/corpse_ghoul2_item"
        Goblin = "scripts/items/misc/corpse_goblin1_item"
        GoblinShaman = "scripts/items/misc/corpse_goblin2_item"
        GoblinLeader = "scripts/items/misc/corpse_goblin3_item"
        Hexe = "scripts/items/misc/corpse_goblin3_item"
        LegendHexeLeader = "scripts/items/misc/corpse_goblin3_item"
        Hyena = "scripts/items/misc/corpse_hyena_item"
        SandGolem = "scripts/items/misc/corpse_ifrit_item"
        Lindwurm = "scripts/items/misc/corpse_lindwurm_item"
        LegendStollwurm = "scripts/items/misc/corpse_lindwurm2_item"
        LegendMummy = "scripts/items/misc/corpse_mummy_item"
        OrcYoung = "scripts/items/misc/corpse_orc_item"
        OrcWarrior = "scripts/items/misc/corpse_orc2_item"
        OrcBerserker = "scripts/items/misc/corpse_orc2_item"
        OrcBehemoth = "scripts/items/misc/corpse_orc3_item"
        OrcWarlord = "scripts/items/misc/corpse_orc3_item"
        Schrat = "scripts/items/misc/corpse_schrat_item"
        LegendGreenwoodSchrat = "scripts/items/misc/corpse_schrat2_item"
        Serpent = "scripts/items/misc/corpse_serpent_item"
        Skeleton = "scripts/items/misc/corpse_skeleton_item"
        SkeletonPriest = "scripts/items/misc/corpse_skeleton3_item"
        SkeletonBoss = "scripts/items/misc/skeleton_boss"
        Spider = "scripts/items/misc/corpse_spider_item"
        LegendRedbackSpider = "scripts/items/misc/corpse_spider2_item"
        Unhold = "scripts/items/misc/corpse_unhold_item"
        UnholdFrost = "scripts/items/misc/corpse_unhold2_item"
        UnholdBog = "scripts/items/misc/corpse_unhold3_item"
        LegendRockUnhold = "scripts/items/misc/corpse_unhold4_item"
        Vampire = "scripts/items/misc/corpse_vampire_item"
        LegendVampireLord = "scripts/items/misc/corpse_vampire2_item"
        Zombie = "scripts/items/misc/corpse_zombie_item"
        ZombieKnight = "scripts/items/misc/corpse_zombie2_item"
        ZombieNecromancer = "scripts/items/misc/corpse_necro_item"
        BasiliskDrone = "scripts/items/misc/corpse_basilisk_drone_item"
        BasiliskSentry = "scripts/items/misc/corpse_basilisk_sentry_item"
	}
}